### ISSUE TITLE
Crash with BreadcrumbStore.add ?

### ISSUE THREAD

**Issue by gabek** [getsentry/sentry-swift#56] opened 2016-09-01 20:12 UTC
I'm seeing periodic crash reports come in pointing to a really simple use of Breadcrumb.  It seems to be rare and random.  I'm curious if this is something anybody has seen before.

```
let breadcrumb = Breadcrumb(category: "Networking", url: url, method: "POST")
sentry?.breadcrumbs.add(breadcrumb)
```

```
SentrySwift.BreadcrumbStore.add (SentrySwift.Breadcrumb) -> ()
objc_msgSend() selector name: retain
BreadcrumbStore.swift, line 0
```

**Comment by joshdholtz** [comment] 2016-09-01 20:29
@gabek I have not seen this before so thanks for reporting it! It appears that its a memory issues (possibly retain cycle somewhere) 💀  I will take a look through the code and see if I can diagnose where this might be happening. Thanks again!

**Comment by HazAT** [comment] 2016-11-15 09:24
We were not able to reproduce it, nevertheless we added a test which writes large sets of breadcrumbs in the store.
If you still experience the problem, please report it again ... closing this for now.

**Closed by HazAT** 2016-11-15 09:24 UTC
